### ISSUE TITLE
Better keyboard navigation in the menu

### ISSUE THREAD

**Issue by FichteFoll** [po5/memo#14]
Not sure how much of this would lie in uosc's responsibility (which I am using), but then it wouldn't apply to the non-usoc menu.

Anyway, after opening the recent file (or url) history and not seeing the video you are about to open on the first page, I would like to immediately move to the next page, e.g. using the page down key. Similarly, moving back a page using Page Up would be very useful.

Another nice idea would be binding the number keys 1 to 0 to select the nth item (with 0 => 10th) to immediately select that item once you found it. This isn't usually something you'd use in a uosc menu, but I imagine it would be quite useful for listings like this.

Keyboard navigation is currently possible using arrow keys (and page down to scroll multiple items at a time), but it feels very unintuitive to use the right arrow after selecting the "Newer entries <" entry to go … left. It may also be a better idea to have the "Newer entries >" entry as the first item to make it easier to differentiate the two pagination items and have a more natural scrolling feeling.

**Comment by po5** [comment]
> it feels very unintuitive to use the right arrow after selecting the "Newer entries <" entry to go … left.

That is a uosc limitation. Left arrow key maps to "go back up the menu tree/close top level menu".  
For this reason we provide `memo-prev` and `memo-next` keybinds, that can be used to flip through pages without having to scroll the menu.  
I haven't tried it but it may be possible to add our own forced keybind for left arrow. I'd rather not override uosc's controls though, can get confusing.

Could move navigation to the top, but we don't know beforehand if the navigation will end up being necessary so we'd either remove it after loading finishes (causing the user's selection to jump around), or gray it out (+some "No more pages" text?).  
This also requires setting the initial selected index to be past controls (to be on the current item), and to me it feels weird not starting at the first menu item.

Ideally we'd have an infinitely scrolling menu and no pagination, but that's not realistic unless uosc adds a way for us to know how far the menu has been scrolled. It could also work nicely with uosc's planned menu search feature.  
Some feature requests for https://github.com/tomasklaen/uosc/issues/587, we'll see if they get accepted :^)  
The vanilla osc can be updated for feature parity later.

> binding the number keys 1 to 0 to select the nth item

Keyboard shortcuts for specific menu items aren't supported by uosc, but we could add our own forced keybinds when the menu is open to make it work with both uosc and vanilla menu.  
Would need to fit a 2nd hint somewhere for the shortcut key. Note we can't make every item accessible, as the user can configure any number of entries per page.

**Comment by po5** [comment]
Possibly solved with the introduction of instant feedback search?

**Comment by FichteFoll** [comment]
Yeah, I just tried it out and instant search works really well here. Praise uosc. :pray:

**Comment by po5** [comment]
You can use `memo-next` and `memo-prev` keybinds to navigate the menus without having to directly interact with them. You can replace the main history key with `memo-next` if you often find yourself going to the next page. It'll open the menu, then act as a next button. Close with ESC.
