### ISSUE TITLE
Show the current page number in the menu title

### ISSUE THREAD

**Issue by FichteFoll** [po5/memo#15]
It would help the general orientation inside the history if the current page number was visible. Additionally, the total number of pages could be displayed to give a relative sense of where the current page stands, which you already get from one bount (that being the first) but not from the other.

All pagination implementations I can think of that are not infinite, i.e. don't have the necessary information available, have an indication of the current and the number of total pages, so it's not unusual.

**Comment by po5** [comment]
The total page count is not available to us until we parse the entire history file, which gets way too costly fast. It can't be estimated as entries are variable length, and deduplication makes it impossible to know how many final menu entries they'll map to.

Current page number makes sense, can add that to the menu title.
