### ISSUE TITLE
Show up history when launching mpv

### ISSUE THREAD

**Issue by da3dsoul1** [po5/memo#16]
I have a feature request to show history menu when launching mpv, is it possible with your script?

Alternative script simplehistory does this by default https://github.com/Eisa01/mpv-scripts

**Comment by christoph-heinrich** [comment]
Create a new lua file in your config with the following content
```lua
mp.command('script-binding memo/memo-history')
```

**Comment by po5** [comment]
I think the issue is about opening the history if no file is selected? That's what SimpleHistory does.

**Comment by christoph-heinrich** [comment]
In that case
```lua
mp.observe_property('idle-active', 'bool', function(_, val)
    if not val then return end
    mp.command('script-binding memo/memo-history')
end)

**Comment by po5** [comment]
Can be achieved with the following auto-profies. I may add an option for this after the search refactor as I don't like the behavior when the menu is already open.

```lua
[memo-idle]
profile-cond=idle_active
input-commands=script-binding memo-next

[memo-active]
profile-cond=not idle_active
input-commands=
```
