### ISSUE TITLE
Problems with `osd-back-color`

### ISSUE THREAD

**Issue by christoph-heinrich** [po5/memo#18]
While testing #17 I noticed that your menu doesn't play nice with `osd-back-color`. I think it's that bad because for each thing `ass:new_event()` is called, and now each of those gets it's own background.

Screenshot with `osd-back-color=0/0/0/0.7`
![image](https://github.com/po5/memo/assets/8932183/c7cf7977-1220-4611-ba49-fd728fb9f3ed)

In quality-menu I fixed it with a `\\rDefault` to get rid of all mpv provided styling, but I don't know if you want to do that.

**Comment by po5** [comment]
Will have to prevent mpv's own styling. We explicitly position every line (and icon) which requires separate events. This is to prevent non-latin characters from affecting the baseline and messing up our scroll alignment.
