### ISSUE TITLE
case insensitive search not working with upper-case accented letters?

### ISSUE THREAD

**Issue by xfzv** [po5/memo#26]
Example:

1. Search for `word` - returns either `word` or `Word` matches :heavy_check_mark:
2. Search for `café` - only returns `café` matches but not `CAFÉ` :x:
3. Search for `CAFÉ` - only returns `CAFÉ` matches but not `café` :x:

**Comment by po5** [comment]
Lua issue, but probably can find code capable of handling that.
```
> a = "CAFÉ"
> a:lower()
cafÉ
```

**Comment by christoph-heinrich** [comment]
Related https://github.com/tomasklaen/uosc/discussions/656
