### ISSUE TITLE
Ignore missing videos

### ISSUE THREAD

**Issue by Zabooby** [po5/memo#3]
If a video is already listed in the menu, and is moved to a different folder it still shows up in the menu, and clicking it does nothing. 

Would it be possible to somehow track the file moved, or is that infinitely harder than just ignoring missing files? 

For example I have a folder called Videos, where my torrents are downloaded, using [webtorrent-mpv-hook](https://github.com/mrxdst/webtorrent-mpv-hook). After downloading I move the video into either my shows or movies subfolder. Could the script track this movement, so the initial menu entry still works?

**Comment by po5** [comment]
The script checks if files exist at whatever location they were registered at. If you move a file, it should disappear.
Maybe the whole deletion detection isn't working on your system? Please try deleting a file and see if it shows up.

**Comment by Zabooby** [comment]
Ok, so deleted/missing files are updated in the menu like you said, the problem I'm facing is with the webtorrent hook script linked above. 

The menu doesn't update when downloaded content is moved to different folders.
