### ISSUE TITLE
Seems to infinitely buffer when URIs are in history

### ISSUE THREAD

**Issue by brian6932** [po5/memo#30]
I Have a stream in `memo-history.log` that looks like
```
unix_timestamp,,,URI
```
it causes memo to buffer infinitely, once that line is deleted it works fine.

**Comment by po5** [comment]
Are there any errors in console? (Backtick key by default, or open mpv through a terminal)  
Can you provide a sample line that triggers this bug? Replace with an example domain and path, so long as you confirm it still triggers the bug.

**Comment by brian6932** [comment]
And I can't seem to reproduce this today :suspect: maybe there was something specific with the URIs that were breaking it, not sure. I'll close this, and reopen once I can repro.
