### ISSUE TITLE
Adding memo-clear to clear entire history

### ISSUE THREAD

**Issue by Mark-Joy** [po5/memo#37]
I just keep history only for sometime. After a period of time (complete watching remaining videos), I usually clear the entire history.
Please add this feature. I think some users may benefit from it.

**Comment by po5** [comment]
You can set up [a keybind](https://mpv.io/manual/master/#command-interface-[-]]]) in input.conf with something like `run rm /path/to/memo-history.log`

**Comment by Mark-Joy** [comment]
Hmnn.. Why didn't I think about it?
Thank you :)
