### ISSUE TITLE
Pagination(older/newer entries) not working after uosc 5.3.0

### ISSUE THREAD

**Issue by debugzxcv** [po5/memo#39]
https://github.com/tomasklaen/uosc/releases/tag/5.3.0

**Comment by po5** [comment]
I've been aware of an issue with pagination before the merge https://github.com/tomasklaen/uosc/pull/936#issuecomment-2246433886 but haven't checked it since.

**Comment by po5** [comment]
Fixed on the uosc side. https://github.com/tomasklaen/uosc/commit/e4e8f077cfbb43c7e952564c2dfd8ef53d9872f6
