### ISSUE TITLE
Videos opened with webtorrent-mpv-hook script, stay in menu even when moved

### ISSUE THREAD

**Issue by Zabooby** [po5/memo#4]
[webtorrent-mpv-hook](https://github.com/mrxdst/webtorrent-mpv-hook) 

Any ideas?

**Comment by po5** [comment]
Is the path saved as `null://` in memo-history.log? Looks like we just need to ignore that protocol.  
https://github.com/mrxdst/webtorrent-mpv-hook/blob/master/src/webtorrent.ts#L137

**Comment by Zabooby** [comment]
The paths are saved as `http://localhost:8888/webtorrent/`.

**Comment by po5** [comment]
Then I am not implementing anything for this. Any service could be running on localhost:8888, not just webtorrent.  
You can already exclude these links from being saved with auto profiles, for your setup.  
https://github.com/po5/memo#disabling-for-specific-directories

**Comment by Zabooby** [comment]
No problem, I guess I can just make a subfolder to save torrents and then exclude that folder from memo.

**Comment by po5** [comment]
I mean that you can exclude the webtorrent urls from being saved.

**Comment by Zabooby** [comment]
Like this?

```
script-opts-append=memo-enabled=yes

[dont-log-my-porn]
profile-cond=string.match(string.lower(string.gsub(require "mp.utils".join_path(get("working-directory", ""), get("path", "")), string.gsub(get("filename", ""), "([^%w])", "%%%1").."$", "")), "null://")~=nil
profile-restore=copy-equal
script-opts-append=memo-enabled=no
```

**Comment by po5** [comment]
no, you'd want to exclude `http://localhost:8888/webtorrent/` or just `webtorrent`.

**Comment by Zabooby** [comment]
Works perfectly!

**Comment by Zabooby** [comment]
The new autoprofile (copied from the readme) doesn't work for me. 
```

[Webtorrent-Entries]
profile-cond=(function() local ignored, path = {"webtorrent"}, get("path", "") path = ((path:find("^%a[%w.+-]-://") or path:find("^%a[%w.+-]-:%?")) and path or require "mp.utils".join_path(get("working-directory", ""), path)):sub(1, -get("filename", ""):len()-1):lower() for _, ig in ipairs(ignored) do if path:find(ig, 1, true) then return true end end end)()
profile-restore=copy-equal
script-opts-append=memo-enabled=no
```
