### ISSUE TITLE
[Feature Request] : save yt video title in menu

### ISSUE THREAD

**Issue by NaiveInvestigator** [po5/memo#5]
as of now if i try to play a yt vid through the menu only the url is shown, which is not helpful as i dont know which link is what.

![image](https://github.com/po5/memo/assets/72654596/93ed3aa1-984b-4be4-88a9-e3fd721ad174)

recent menu saves the title
![image](https://github.com/po5/memo/assets/72654596/d380cddd-4764-49ba-a12f-5d5bb678d78d)

i think if we save the yt title also it would be easier for people to identify what to choose.

**Comment by po5** [comment]
It does work, update your mpv. https://github.com/mpv-player/mpv/commit/34a04d056764f4f1447d39b60be56f02253831f8
It's a better solution than looking at `media-title`.
