### ISSUE TITLE
Save watching in Bookmark, and displays it in a nice menu, integrated with uosc.

### ISSUE THREAD

**Issue by candrapersada** [po5/memo#6]
is there a feature to save watching in Bookmarks without being deleted automatically like [SimpleBookmark](https://github.com/Eisa01/mpv-scripts#simplebookmark)?

**Comment by po5** [comment]
Can you expand on what functionality you're asking for?

Do you want a menu that only contains manually added items?  
Do you want to jump to any of them through a custom keybind?  
Are you asking for the ability to save playback time?

**Comment by candrapersada** [comment]
> Do you want a menu that only contains manually added items?

yes like Bookmark
![baseline_bookmark_add_white_24dp](https://github.com/po5/memo/assets/36833664/e3f12397-86a4-497b-bfb1-17d019242850)

**Comment by po5** [comment]
Low effort issue, didn't elaborate. Find someone else to make a bookmark script that integrates with uosc, or someone who can type up a proper issue.
