### ISSUE TITLE
Suggest adding a shortcut key to delete history entries

### ISSUE THREAD

**Issue by DrZhang1208** [po5/memo#7]
Suggest adding a shortcut key to delete history entries

**Comment by po5** [comment]
UI concerns: would rather wait until uosc adds the ability to define secondary actions, while still allowing for quick access of the primary action. https://github.com/tomasklaen/uosc/issues/475  
Alternatively we could have a key for a dedicated deletion menu but it would be easy to confuse with the main menu and require a new keybind.

Usage concerns: Would this remove only one line corresponding to the selected entry? Likely not what most users want. Or all lines that match this path? Forcing us to read the entire history file on every deletion.  
Should this behavior change depending on the `hide_same_dir` option?

Implementation concerns: We would either have to blank out entries in-place (is this possible in lua?), leaking deleted entries' length, or rewrite the entire file on every deletion, which is unreliable and will likely lead to a completely wiped history once in a while.  
See other scripts that struggle with a full rewrite approach: https://github.com/d87/mpv-persist-properties/pull/5, https://github.com/natural-harmonia-gropius/recent-menu/issues/13

This doesn't seem possible to implement in a reliable and efficient way, I trust external text editors much more for this task.  
If you are often running into files you'd rather not log, and they don't follow a particular pattern, you can use in-memory history with an empty `history_path` option.  
Would a hard limit on logged entries also work for you? I'd feel much more confident rewriting the entire history file if it was always kept to a workable size.  
If we added a setting like `total_entries=10`. Your mistakenly logged file would automatically go away after 10 other files have been played.

Curious what you think.

**Comment by po5** [comment]
Closing as this would be highly impractical to implement, and user has shown no interest.  
Consider using in-memory history.
