### ISSUE TITLE
[FR] Keybinding to add selected entry to the playlist

### ISSUE THREAD

**Issue by xfzv** [po5/memo#8]
With current behavior, pressing either "return" or right arrow will start playing the selected entry. It would be nice if we could add it to the playlist with another keybinding instead, so that the current playback isn't stopped.

Maybe not useful but I'm using [Eisa01/SmartCopyPaste.lua](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SmartCopyPaste.lua), which allows to do this.

Pretty similar to #7 but maybe it's easier to implement? Anyway, that's just an idea.

**Comment by po5** [comment]
Done. You can of course change the keybinds if you'd rather have it append by default.  
Note that it will only add the entry if it wasn't already in the playlist.
